apiVersion: v1
kind: Service
metadata:
  name: regsds-frontend
spec: 
  selector:
    app: regsds-frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http