apiVersion: v1
kind: Service
metadata:
  name: regsds-course-scheduler
spec: 
  selector:
    app: regsds-course-scheduler
  type: LoadBalancer
  ports:
    - name: http
      port: 5001
      protocol: TCP
      targetPort: http