apiVersion: v1
kind: Service
metadata:
  name: regsds-grade-assessment
spec: 
  selector:
    app: regsds-grade-assessment
  type: LoadBalancer
  ports:
    - name: http
      port: 5003
      protocol: TCP
      targetPort: http