apiVersion: apps/v1
kind: Deployment
metadata:
  name: regsds-pdf-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regsds-pdf-generator
  template:
    metadata:
      labels:
        app: regsds-pdf-generator
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: worker
        pdf-generator: "true"
      volumes:
        - name: regsds-pdf-generator
          configMap: 
            name: regsds-pdf-generator
      containers:
      - name: regsds-pdf-generator
        image: nitiwatowen/regsds-pdf-generator
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: regsds-pdf-generator
        ports: 
          - name: http
            containerPort: 5004
            
