apiVersion: v1
kind: Service
metadata:
  name: regsds-pdf-generator
spec: 
  selector:
    app: regsds-pdf-generator
  type: LoadBalancer
  ports:
    - name: http
      port: 5004
      protocol: TCP
      targetPort: http