apiVersion: v1
kind: Service
metadata:
  name: regsds-grade-calculator
spec: 
  selector:
    app: regsds-grade-calculator
  type: LoadBalancer
  ports:
    - name: http
      port: 5002
      protocol: TCP
      targetPort: http